jenkins-server:
  ports:
  - 8181:8080/tcp
  - 5000:5000/tcp
  labels:
    io.rancher.sidekicks: jenkins-data-container
    io.rancher.container.pull_image: always
  tty: true
  image: growthhackers/jenkins2-docker
  volumes_from:
  - jenkins-data-container
  stdin_open: true
jenkins-data-container:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.start_once: 'true'
  tty: true
  image: growthhackers/jenkins2-docker-data
  stdin_open: true